    Type: AWS::DynamoDB::Table
    Properties:
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: color
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: Widget-by-Color
          KeySchema:
            - AttributeName: color
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: True
